// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Post from "./post.bs.js";
import * as React from "react";
import * as PostItem from "./PostItem.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";

function s(prim) {
  return prim;
}

function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* DeleteLater */0 :
        return {
                posts: state.posts,
                forDeletion: Belt_MapString.set(state.forDeletion, action._0.id, action._1)
              };
    case /* DeleteAbort */1 :
        return {
                posts: state.posts.concat([action._0]),
                forDeletion: state.forDeletion
              };
    case /* DeleteNow */2 :
        var post = action._0;
        return {
                posts: state.posts.filter(function (arrPosts) {
                      return post.id !== arrPosts.id;
                    }),
                forDeletion: state.forDeletion
              };
    
  }
}

var initialState = {
  posts: Post.examples,
  forDeletion: undefined
};

function PostFeed(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var $$clearTimeout = function (post) {
    Belt_Option.map(Belt_MapString.get(state.forDeletion, post.id), window.clearTimeout);
    
  };
  var posts = Belt_Array.map(state.posts, (function (x) {
          return React.createElement(PostItem.make, {
                      post: x,
                      dispatch: dispatch,
                      clearTimeout: $$clearTimeout,
                      key: x.id
                    });
        }));
  return React.createElement("div", {
              className: "max-w-3xl mx-auto mt-8 relative"
            }, React.createElement("div", undefined, posts));
}

var make = PostFeed;

export {
  s ,
  reducer ,
  initialState ,
  make ,
  
}
/* Post Not a pure module */
