// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Nanoid from "nanoid";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function s(prim) {
  return prim;
}

function PostItem(Props) {
  var post = Props.post;
  var $$clearTimeout = Props.clearTimeout;
  var match = React.useState(function () {
        return false;
      });
  var setHidePost = match[1];
  var setDeletion = function (param) {
    return Curry._1(setHidePost, (function (param) {
                  return true;
                }));
  };
  var abortDeletion = function (param) {
    Curry._1($$clearTimeout, post);
    return Curry._1(setHidePost, (function (param) {
                  return false;
                }));
  };
  if (match[0]) {
    return React.createElement("div", {
                className: "relative bg-yellow-100 px-8 py-4 mb-4 h-40"
              }, React.createElement("p", {
                    className: "text-center white mb-1"
                  }, "This post from " + post.title + " by " + post.author + " will be permanently removed in 10 seconds."), React.createElement("div", {
                    className: "flex justify-center"
                  }, React.createElement("button", {
                        className: "mr-4 mt-4 bg-yellow-500 hover:bg-yellow-900 text-white py-2 px-4",
                        onClick: abortDeletion
                      }, "Restore"), React.createElement("button", {
                        className: "mr-4 mt-4 bg-red-500 hover:bg-red-900 text-white py-2 px-4"
                      }, "Delete Immediately")), React.createElement("div", {
                    className: "bg-red-500 h-2 w-full absolute top-0 left-0 progress"
                  }));
  } else {
    return React.createElement("div", {
                className: "bg-green-700 hover:bg-green-900 text-gray-300 hover:text-gray-100 px-8 py-4 mb-4"
              }, React.createElement("h2", {
                    className: "text-2xl mb-1"
                  }, post.title), React.createElement("h3", {
                    className: "mb-4"
                  }, post.author), Belt_Array.map(post.text, (function (para) {
                      return React.createElement("p", {
                                  key: Nanoid.nanoid(),
                                  className: "mb-1 text-sm"
                                }, para);
                    })), React.createElement("button", {
                    className: "mr-4 mt-4 bg-red-500 hover:bg-red-900 text-white py-2 px-4",
                    onClick: setDeletion
                  }, "Remove this post"));
  }
}

var make = PostItem;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
